# Generated by Django 4.1 on 2023-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviculture', '0005_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
